$ python -m packages.appflow_tracer.tracing ;
<frozen runpy>:128: RuntimeWarning: 'packages.appflow_tracer.tracing' found in sys.modules after import of package 'packages.appflow_tracer', but prior to execution of 'packages.appflow_tracer.tracing'; this may result in unpredictable behaviour
[CALL] packages/appflow_tracer/tracing ( file_utils.manage_logfiles(CONFIGS) )
[CALL] packages/appflow_tracer/tracing (setup_logging)[219] -> packages/appflow_tracer/lib/file_utils (manage_logfiles)[96]
{
    "configs": {
        "colors": {
            "CALL": "\u001b[92m",
            "RETURN": "\u001b[93m",
            "IMPORT": "\u001b[94m",
            "DEBUG": "\u001b[96m",
            "INFO": "\u001b[97m",
            "WARNING": "\u001b[91m",
            "ERROR": "\u001b[31m",
            "CRITICAL": "\u001b[41m",
            "RESET": "\u001b[0m"
        },
        "logging": {
            "enable": true,
            "max_logfiles": 5,
            "package_name": "appflow_tracer",
            "module_name": "tracing",
            "logs_dirname": "logs/appflow_tracer",
            "log_filename": "logs/appflow_tracer/tracing_20250217215519.log"
        },
        "tracing": {
            "enable": true,
            "json": {
                "compressed": false
            }
        },
        "events": {
            "call": true,
            "return": true,
            "import": false
        },
        "stats": {
            "created": "2025-02-18T04:36:09.546924",
            "updated": "2025-02-18T04:55:19.917623+00:00"
        }
    }
}
[CALL] packages/appflow_tracer/lib/file_utils ( log_files = sorted( )
[CALL] packages/appflow_tracer/lib/file_utils (manage_logfiles)[135] -> packages/appflow_tracer/lib/file_utils (<lambda>)[137]
{
    "f": "logs/appflow_tracer/tracing_20250217215519.log"
}
[RETURN] packages/appflow_tracer/lib/file_utils[137] ( key=lambda f:f.stat().st_mtime ) -> float:
1739854519.9438193
[RETURN] packages/appflow_tracer/lib/file_utils[152] ( return deleted_logs ) -> list:
